version: '3.7'

services:
  fckalgos-frontend:
    build:
      context: .
    expose:
      - "3005"
    networks:
      - fck-algos-shared-net

networks:
  fck-algos-shared-net:
    external: true

